Update CLI/CI script and fix deprecated methods.

diff --git a/.github/workflows/syllabus-ci.yml b/.github/workflows/syllabus-ci.yml
--- a/.github/workflows/syllabus-ci.yml
+++ b/.github/workflows/syllabus-ci.yml
@@ -1,14 +1,21 @@
+# Title of the workflow
 name: Moodle Plugin CI
 
+# Run this workflow every time a new commit pushed to your repository or PR
+# created.
 on: [push, pull_request]
 
 jobs:
+  # Set the job key. The key is displayed as the job name
+  # when a job name is not provided
   test:
+    # Virtual environment to use.
     runs-on: ubuntu-22.04
 
+    # DB services you need for testing.
     services:
       postgres:
-        image: postgres:13
+        image: postgres:15
         env:
           POSTGRES_USER: 'postgres'
           POSTGRES_HOST_AUTH_METHOD: 'trust'
@@ -27,87 +34,152 @@ jobs:
           - 3306:3306
         options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
 
+    # Determines build matrix. This is a list of PHP versions, databases and
+    # branches to test our project against. For each combination a separate
+    # build will be created. For example below 6 builds will be created in
+    # total (7.4-pgsql, 7.4-mariadb, 8.0-pgsql, 8.0-mariadb, etc.). If we add
+    # another branch, total number of builds will become 12.
     strategy:
       fail-fast: false
       matrix:
-        php: ['7.4', '8.0', '8.1']
-        moodle-branch: ['MOODLE_401_STABLE']
+        php: ['8.2', '8.3', '8.4']
+        moodle-branch: ['MOODLE_501_STABLE']
         database: [pgsql, mariadb]
 
+    # There is an alternative way allowing to define explicitly define which php, moodle-branch
+    # and database to use:
+    #
+    # matrix:
+    #   include:
+    #     - php: '8.0'
+    #       moodle-branch: 'MOODLE_401_STABLE'
+    #       database: pgsql
+    #     - php: '8.0'
+    #       moodle-branch: 'MOODLE_400_STABLE'
+    #       database: mariadb
+    #     - php: '7.4'
+    #       moodle-branch: 'MOODLE_311_STABLE'
+    #       database: pgsql
+
     steps:
+      # Check out this repository code in ./plugin directory
       - name: Check out repository code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           path: plugin
 
+      # Install PHP of required version. For possible options see https://github.com/shivammathur/setup-php
       - name: Setup PHP ${{ matrix.php }}
         uses: shivammathur/setup-php@v2
         with:
           php-version: ${{ matrix.php }}
           extensions: ${{ matrix.extensions }}
-          ini-values: max_input_vars=5000
+          # ini-values: max_input_vars=5000
           # If you are not using code coverage, keep "none". Otherwise, use "pcov" (Moodle 3.10 and up) or "xdebug".
           # If you try to use code coverage with "none", it will fallback to phpdbg (which has known problems).
+          ini-values: max_input_vars=5000, memory_limit=-1
           coverage: none
 
+      # Install this project into a directory called "ci", updating PATH and
+      # locale, define nvm location.
       - name: Initialise moodle-plugin-ci
         run: |
+          # Force composer to ignore memory boundaries and set a higher process timeout
+          export COMPOSER_MEMORY_LIMIT=-1
+          composer config --global process-timeout 2000
+
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
           echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
 
+      # Run the default install.
+      # Optionally, it is possible to specify a different Moodle repo to use
+      # (https://github.com/moodle/moodle.git is used by default) and define
+      # ignore directives or any other env vars for install step.  For more
+      # details on configuring for specific requirements please refer to the
+      # 'Help' page.
+      #
+      # env:
+      #   MOODLE_REPO=https://github.com/username/moodle.git
+      #   IGNORE_PATHS: 'ignore'
+      #   IGNORE_NAMES: 'ignore_name.php'
+      #   MUSTACHE_IGNORE_NAMES: 'broken.mustache'
+      #   CODECHECKER_IGNORE_PATHS: 'ignoreme'
+      #   CODECHECKER_IGNORE_NAMES: 'ignoreme_name.php'
+      #
+      # Other env vars are available for install, namely:
+      #   - DB_USER / DB_PASS / DB_NAME / DB_HOST / DB_PORT: used
+      #     by install to feed the corresponding --db-xxxx options.
+      #   - MOODLE_APP: used to install dependencies to run Behat tests
+      #     using the Moodle App.
       - name: Install moodle-plugin-ci
         run: |
           moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
         env:
           DB: ${{ matrix.database }}
           MOODLE_BRANCH: ${{ matrix.moodle-branch }}
+          # Uncomment this to run Behat tests using the Moodle App.
+          # MOODLE_APP: 'true'
 
+      # Steps that are run for the purpose of testing.  Any of these steps
+      # can be re-ordered or removed to your liking.  And of course, you can
+      # add any of your own custom steps.
       - name: PHP Lint
-        if: ${{ always() }}
+        if: ${{ !cancelled() }} # prevents CI run stopping if step failed.
         run: moodle-plugin-ci phplint
 
-      - name: PHP Copy/Paste Detector
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpcpd
-
       - name: PHP Mess Detector
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ always() }}
+        continue-on-error: true
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci phpmd
 
       - name: Moodle Code Checker
-        if: ${{ always() }}
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci phpcs --max-warnings 0
 
       - name: Moodle PHPDoc Checker
-        if: ${{ always() }}
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci phpdoc --max-warnings 0
 
       - name: Validating
-        if: ${{ always() }}
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci validate
 
       - name: Check upgrade savepoints
-        if: ${{ always() }}
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci savepoints
 
       - name: Mustache Lint
-        if: ${{ always() }}
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci mustache
 
       - name: Grunt
-        if: ${{ always() }}
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci grunt --max-lint-warnings 0
 
       - name: PHPUnit tests
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpunit --fail-on-warning
+        if: ${{ !cancelled() }}
+        run: moodle-plugin-ci phpunit
 
       - name: Behat features
-        if: ${{ always() }}
+        id: behat
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci behat --profile chrome
 
+      # This step allows to upload Behat faildump (screenshots) as workflow artifact
+      # so it can be downloaded and inspected. You don't need this step if you
+      # are not running Behat test. Artifact will be retained for 7 days.
+      - name: Upload Behat Faildump
+        if: ${{ failure() && steps.behat.outcome == 'failure' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: Behat Faildump (${{ join(matrix.*, ', ') }})
+          path: ${{ github.workspace }}/moodledata/behat_dump
+          retention-days: 7
+          if-no-files-found: ignore
+
+      - name: Mark cancelled jobs as failed.
+        if: ${{ cancelled() }}
+        run: exit 1
